version: '3.8'

services:
  authentification-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: authentification
      MYSQL_USER: authentification
      MYSQL_PASSWORD: authentification_password

  projets-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: projets
      MYSQL_USER: projets
      MYSQL_PASSWORD: projets_password

  equipes-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: equipes
      MYSQL_USER: equipes
      MYSQL_PASSWORD: equipes_password

  propositions-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: propositions
      MYSQL_USER: propositions
      MYSQL_PASSWORD: propositions_password

  votes-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: votes
      MYSQL_USER: votes
      MYSQL_PASSWORD: votes_password

  authentification-api:
    build:
      context: ./authentification
      dockerfile: ./Dockerfile.dev
    depends_on:
      - authentification-db
    ports:
      - "8081:8080"
    volumes:
      - ./authentification:/app
      - ~/.m2:/root/.m2

  projets-api:
    build:
      context: ./projets
      dockerfile: ./Dockerfile.dev
    depends_on:
      - projets-db
    ports:
      - "8082:8080"
    volumes:
      - ./projets:/app
      - ~/.m2:/root/.m2

  equipes-api:
    build:
      context: ./equipes
      dockerfile: ./Dockerfile.dev
    depends_on:
      - equipes-db
    ports:
      - "8083:8080"
    volumes:
      - ./equipes:/app
      - ~/.m2:/root/.m2

  propositions-api:
    build:
      context: ./propositions
      dockerfile: ./Dockerfile.dev
    depends_on:
      - propositions-db
    ports:
      - "8084:8080"
    volumes:
      - ./propositions:/app
      - ~/.m2:/root/.m2

  votes-api:
    build:
      context: ./votes
      dockerfile: ./Dockerfile.dev
    depends_on:
      - votes-db
    ports:
      - "8085:8080"
    volumes:
      - ./votes:/app
      - ~/.m2:/root/.m2
